version: "3.8"
services:
  gophkeeper:
    container_name: gophkeeper
    image: gophkeeper-server:develop
    environment:
      DATABASE_DSN: ${DATABASE_DSN}
    ports:
      - "8080:8080"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
    depends_on:
      - pgserver
    restart: always

  pgserver:
    container_name: pg-gophkeeper
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
      - "5477:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

volumes:
  postgres-data:
